{% set name = "fpart" %}
{% set version = "1.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/martymac/fpart/archive/refs/tags/{{ name }}-{{ version }}.tar.gz
  sha256: da4cd97365a2ebb3d0ee7e634c022eb21321ee5b6ab213d796fcbb01f28d9759

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - autoconf
    - automake
  run:
    - gawk
    - findutils
    - coreutils
    - sed
    - rsync

test:
  commands:
    - fpart -h

about:
  home: https://www.fpart.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING
  summary: Sort files and pack them into partitions

extra:
  recipe-maintainers:
    - izahn
